### ISSUE TITLE
Feature request - Configurable tag lists for NSFW

### ISSUE THREAD

**Issue by lillelilje** [Meisterlala/NekoLife#4]
Hi!
It would be fantastic if we were able to customize:

- Tags that are used for searching
- Tags that are used to block results

A simple UI that lets you add/remove words would be great, but a config file which a user has to manually edit should suffice imo.

Is this something you'd be up for implementing? Either on your own or with a PR?

**Comment by Meisterlala** [comment]
What exactly do you mean by that?

You can currently filter tweets and exclude certain hashtags like this:
`#gposers -#miqote -#aura -#lala -#lalafell -nude -(#meme OR funny)`
Check out the [Twitter advanced search](https://twitter.com/search-advanced) to easily create more complex searches.

Its not really possible to filter a search by username (`@nasa` which shows the last 600 tweets of NASA) like this because of Twitter API limitations.

I would be happy to implement your Ideas. Pull requests are also always welcome.
